//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertChannel) DeepCopyInto(out *AlertChannel) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigSecretRefs != nil {
		in, out := &in.ConfigSecretRefs, &out.ConfigSecretRefs
		*out = make(map[string]v1.SecretKeySelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertChannel.
func (in *AlertChannel) DeepCopy() *AlertChannel {
	if in == nil {
		return nil
	}
	out := new(AlertChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertFired) DeepCopyInto(out *AlertFired) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertFired.
func (in *AlertFired) DeepCopy() *AlertFired {
	if in == nil {
		return nil
	}
	out := new(AlertFired)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyList) DeepCopyInto(out *AutoscalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoscalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyList.
func (in *AutoscalingPolicyList) DeepCopy() *AutoscalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicySpec) DeepCopyInto(out *AutoscalingPolicySpec) {
	*out = *in
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]NodePoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicySpec.
func (in *AutoscalingPolicySpec) DeepCopy() *AutoscalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyStatus) DeepCopyInto(out *AutoscalingPolicyStatus) {
	*out = *in
	if in.LastScaleUpTime != nil {
		in, out := &in.LastScaleUpTime, &out.LastScaleUpTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDownTime != nil {
		in, out := &in.LastScaleDownTime, &out.LastScaleDownTime
		*out = (*in).DeepCopy()
	}
	if in.PredictiveScaling != nil {
		in, out := &in.PredictiveScaling, &out.PredictiveScaling
		*out = new(PredictiveScalingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyStatus.
func (in *AutoscalingPolicyStatus) DeepCopy() *AutoscalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetAlert) DeepCopyInto(out *BudgetAlert) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AlertChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetAlert.
func (in *BudgetAlert) DeepCopy() *BudgetAlert {
	if in == nil {
		return nil
	}
	out := new(BudgetAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetEnforcement) DeepCopyInto(out *BudgetEnforcement) {
	*out = *in
	if in.ThrottleConfig != nil {
		in, out := &in.ThrottleConfig, &out.ThrottleConfig
		*out = new(ThrottleConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetEnforcement.
func (in *BudgetEnforcement) DeepCopy() *BudgetEnforcement {
	if in == nil {
		return nil
	}
	out := new(BudgetEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetScope) DeepCopyInto(out *BudgetScope) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetScope.
func (in *BudgetScope) DeepCopy() *BudgetScope {
	if in == nil {
		return nil
	}
	out := new(BudgetScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostAttribution) DeepCopyInto(out *CostAttribution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostAttribution.
func (in *CostAttribution) DeepCopy() *CostAttribution {
	if in == nil {
		return nil
	}
	out := new(CostAttribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostAttribution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostAttributionList) DeepCopyInto(out *CostAttributionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostAttribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostAttributionList.
func (in *CostAttributionList) DeepCopy() *CostAttributionList {
	if in == nil {
		return nil
	}
	out := new(CostAttributionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostAttributionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostAttributionSpec) DeepCopyInto(out *CostAttributionSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostAttributionSpec.
func (in *CostAttributionSpec) DeepCopy() *CostAttributionSpec {
	if in == nil {
		return nil
	}
	out := new(CostAttributionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostAttributionStatus) DeepCopyInto(out *CostAttributionStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	in.DetailedBreakdown.DeepCopyInto(&out.DetailedBreakdown)
	if in.HistoricalData != nil {
		in, out := &in.HistoricalData, &out.HistoricalData
		*out = make([]CostDataPoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Savings = in.Savings
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostAttributionStatus.
func (in *CostAttributionStatus) DeepCopy() *CostAttributionStatus {
	if in == nil {
		return nil
	}
	out := new(CostAttributionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBreakdown) DeepCopyInto(out *CostBreakdown) {
	*out = *in
	if in.ByNamespace != nil {
		in, out := &in.ByNamespace, &out.ByNamespace
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ByLabel != nil {
		in, out := &in.ByLabel, &out.ByLabel
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ByInstanceType != nil {
		in, out := &in.ByInstanceType, &out.ByInstanceType
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SpotVsOnDemand != nil {
		in, out := &in.SpotVsOnDemand, &out.SpotVsOnDemand
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBreakdown.
func (in *CostBreakdown) DeepCopy() *CostBreakdown {
	if in == nil {
		return nil
	}
	out := new(CostBreakdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBudget) DeepCopyInto(out *CostBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBudget.
func (in *CostBudget) DeepCopy() *CostBudget {
	if in == nil {
		return nil
	}
	out := new(CostBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBudgetList) DeepCopyInto(out *CostBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBudgetList.
func (in *CostBudgetList) DeepCopy() *CostBudgetList {
	if in == nil {
		return nil
	}
	out := new(CostBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBudgetSpec) DeepCopyInto(out *CostBudgetSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]BudgetAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(BudgetEnforcement)
		(*in).DeepCopyInto(*out)
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBudgetSpec.
func (in *CostBudgetSpec) DeepCopy() *CostBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(CostBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostBudgetStatus) DeepCopyInto(out *CostBudgetStatus) {
	*out = *in
	if in.AlertsFired != nil {
		in, out := &in.AlertsFired, &out.AlertsFired
		*out = make([]AlertFired, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExceededSince != nil {
		in, out := &in.ExceededSince, &out.ExceededSince
		*out = (*in).DeepCopy()
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	in.Breakdown.DeepCopyInto(&out.Breakdown)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostBudgetStatus.
func (in *CostBudgetStatus) DeepCopy() *CostBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(CostBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostDataPoint) DeepCopyInto(out *CostDataPoint) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostDataPoint.
func (in *CostDataPoint) DeepCopy() *CostDataPoint {
	if in == nil {
		return nil
	}
	out := new(CostDataPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyCost) DeepCopyInto(out *DailyCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyCost.
func (in *DailyCost) DeepCopy() *DailyCost {
	if in == nil {
		return nil
	}
	out := new(DailyCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetailedBreakdown) DeepCopyInto(out *DetailedBreakdown) {
	*out = *in
	if in.ByPod != nil {
		in, out := &in.ByPod, &out.ByPod
		*out = make(map[string]PodCostInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ByGPUType != nil {
		in, out := &in.ByGPUType, &out.ByGPUType
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ByCapacityType != nil {
		in, out := &in.ByCapacityType, &out.ByCapacityType
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ByNode != nil {
		in, out := &in.ByNode, &out.ByNode
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ByHour != nil {
		in, out := &in.ByHour, &out.ByHour
		*out = make([]HourlyCost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ByDay != nil {
		in, out := &in.ByDay, &out.ByDay
		*out = make([]DailyCost, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetailedBreakdown.
func (in *DetailedBreakdown) DeepCopy() *DetailedBreakdown {
	if in == nil {
		return nil
	}
	out := new(DetailedBreakdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfig) DeepCopyInto(out *GPUNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfig.
func (in *GPUNodeConfig) DeepCopy() *GPUNodeConfig {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigList) DeepCopyInto(out *GPUNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigList.
func (in *GPUNodeConfigList) DeepCopy() *GPUNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigSpec) DeepCopyInto(out *GPUNodeConfigSpec) {
	*out = *in
	if in.MIGProfiles != nil {
		in, out := &in.MIGProfiles, &out.MIGProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigSpec.
func (in *GPUNodeConfigSpec) DeepCopy() *GPUNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeConfigStatus) DeepCopyInto(out *GPUNodeConfigStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.MIGStatus != nil {
		in, out := &in.MIGStatus, &out.MIGStatus
		*out = new(MIGStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.MPSStatus != nil {
		in, out := &in.MPSStatus, &out.MPSStatus
		*out = new(MPSStatusInfo)
		**out = **in
	}
	if in.TimeSlicingStatus != nil {
		in, out := &in.TimeSlicingStatus, &out.TimeSlicingStatus
		*out = new(TimeSlicingStatusInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeConfigStatus.
func (in *GPUNodeConfigStatus) DeepCopy() *GPUNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingPolicy) DeepCopyInto(out *GPUSharingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingPolicy.
func (in *GPUSharingPolicy) DeepCopy() *GPUSharingPolicy {
	if in == nil {
		return nil
	}
	out := new(GPUSharingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUSharingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingPolicyList) DeepCopyInto(out *GPUSharingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUSharingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingPolicyList.
func (in *GPUSharingPolicyList) DeepCopy() *GPUSharingPolicyList {
	if in == nil {
		return nil
	}
	out := new(GPUSharingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUSharingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingPolicySpec) DeepCopyInto(out *GPUSharingPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MIGConfig != nil {
		in, out := &in.MIGConfig, &out.MIGConfig
		*out = new(MIGConfig)
		**out = **in
	}
	if in.MPSConfig != nil {
		in, out := &in.MPSConfig, &out.MPSConfig
		*out = new(MPSConfig)
		**out = **in
	}
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingPolicySpec.
func (in *GPUSharingPolicySpec) DeepCopy() *GPUSharingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GPUSharingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingPolicyStatus) DeepCopyInto(out *GPUSharingPolicyStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingPolicyStatus.
func (in *GPUSharingPolicyStatus) DeepCopy() *GPUSharingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GPUSharingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HourlyCost) DeepCopyInto(out *HourlyCost) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HourlyCost.
func (in *HourlyCost) DeepCopy() *HourlyCost {
	if in == nil {
		return nil
	}
	out := new(HourlyCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MIGConfig) DeepCopyInto(out *MIGConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MIGConfig.
func (in *MIGConfig) DeepCopy() *MIGConfig {
	if in == nil {
		return nil
	}
	out := new(MIGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MIGStatus) DeepCopyInto(out *MIGStatus) {
	*out = *in
	if in.ConfiguredProfiles != nil {
		in, out := &in.ConfiguredProfiles, &out.ConfiguredProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MIGStatus.
func (in *MIGStatus) DeepCopy() *MIGStatus {
	if in == nil {
		return nil
	}
	out := new(MIGStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPSConfig) DeepCopyInto(out *MPSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPSConfig.
func (in *MPSConfig) DeepCopy() *MPSConfig {
	if in == nil {
		return nil
	}
	out := new(MPSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPSStatusInfo) DeepCopyInto(out *MPSStatusInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPSStatusInfo.
func (in *MPSStatusInfo) DeepCopy() *MPSStatusInfo {
	if in == nil {
		return nil
	}
	out := new(MPSStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) {
	*out = *in
	if in.InstanceTypes != nil {
		in, out := &in.InstanceTypes, &out.InstanceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailabilityZones != nil {
		in, out := &in.AvailabilityZones, &out.AvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSpec.
func (in *NodePoolSpec) DeepCopy() *NodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCostInfo) DeepCopyInto(out *PodCostInfo) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCostInfo.
func (in *PodCostInfo) DeepCopy() *PodCostInfo {
	if in == nil {
		return nil
	}
	out := new(PodCostInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingStatus) DeepCopyInto(out *PredictiveScalingStatus) {
	*out = *in
	if in.NextBusyPeriod != nil {
		in, out := &in.NextBusyPeriod, &out.NextBusyPeriod
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingStatus.
func (in *PredictiveScalingStatus) DeepCopy() *PredictiveScalingStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavingsData) DeepCopyInto(out *SavingsData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavingsData.
func (in *SavingsData) DeepCopy() *SavingsData {
	if in == nil {
		return nil
	}
	out := new(SavingsData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleConfig) DeepCopyInto(out *ThrottleConfig) {
	*out = *in
	if in.MaxSpotInstances != nil {
		in, out := &in.MaxSpotInstances, &out.MaxSpotInstances
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleConfig.
func (in *ThrottleConfig) DeepCopy() *ThrottleConfig {
	if in == nil {
		return nil
	}
	out := new(ThrottleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfig) DeepCopyInto(out *TimeSlicingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfig.
func (in *TimeSlicingConfig) DeepCopy() *TimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingStatusInfo) DeepCopyInto(out *TimeSlicingStatusInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingStatusInfo.
func (in *TimeSlicingStatusInfo) DeepCopy() *TimeSlicingStatusInfo {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingStatusInfo)
	in.DeepCopyInto(out)
	return out
}
