version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: controller
    main: ./cmd/controller
    binary: gpu-autoscaler-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Version={{.Version}}
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Commit={{.Commit}}
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Date={{.Date}}

  - id: cli
    main: ./cmd/cli
    binary: gpu-autoscaler
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Version={{.Version}}
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Commit={{.Commit}}
      - -X github.com/gpuautoscaler/gpuautoscaler/pkg/version.Date={{.Date}}

archives:
  - id: controller-archive
    builds:
      - controller
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-controller_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

  - id: cli-archive
    builds:
      - cli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Security Updates
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other Changes
      order: 999

brews:
  - name: gpuautoscaler
    ids:
      - cli
    repository:
      owner: holynakamoto
      name: homebrew-gpuautoscaler
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/holynakamoto/gpuautoscaler
    description: "Kubernetes-native GPU Autoscaler: maximize utilization, minimize cloud costs"
    license: Apache-2.0
    skip_upload: auto
    test: |
      system "#{bin}/gpu-autoscaler", "version"
    install: |
      bin.install "gpu-autoscaler"

release:
  github:
    owner: holynakamoto
    name: gpuautoscaler
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Using Homebrew (macOS/Linux)
    ```bash
    brew install holynakamoto/gpuautoscaler
    ```

    ### Using install script (Linux/macOS)
    ```bash
    curl -sSL https://raw.githubusercontent.com/holynakamoto/gpuautoscaler/main/install.sh | bash
    ```

    ### Using Helm
    ```bash
    helm repo add gpu-autoscaler https://gpuautoscaler.github.io/charts
    helm install gpu-autoscaler gpu-autoscaler/gpu-autoscaler \
      --namespace gpu-autoscaler-system \
      --create-namespace
    ```

    ### Manual Binary Download
    Download the appropriate binary for your platform from the assets below and add it to your PATH.

    **Full Changelog**: https://github.com/gpuautoscaler/gpuautoscaler/compare/{{ .PreviousTag }}...{{ .Tag }}
